import fs from 'node:fs'
import path from 'node:path'
import { expect, openFarming, test } from './fixtures'

for (const appearance of ['light', 'dark', 'paper'] as const) {
  test(`read-only Goal and cancelled tools survive follow-up (${appearance})`, async ({ page, workspaceRoot }, testInfo) => {
    const workspace = path.join(workspaceRoot, 'service-demo')
    fs.mkdirSync(workspace, { recursive: true })
    const create = async () => {
      const response = await page.request.post('/farming/api/control/agents', {
        data: { command: 'codex', workspace, agentRuntimeMode: 'chat' },
      })
      expect(response.ok()).toBeTruthy()
      return (await response.json() as { agentId: string }).agentId
    }
    const id = await create()
    await openFarming(page)
    const row = (agentId: string) => page.locator(`[data-testid="code-agent-row"][data-agent-id="${agentId}"]`)
    await row(id).click()
    await page.locator('body').evaluate((body, value) => { body.dataset.appearance = value }, appearance)
    const input = page.getByTestId('code-acp-composer-input')
    const send = page.getByTestId('code-acp-composer-send')
    await input.fill('goal cancellation fixture')
    await send.click()
    const goal = page.getByTestId('code-agent-goal-driver')
    const plan = page.getByTestId('code-agent-transcript-plan-driver')
    await expect(goal).toContainText('active')
    await expect(plan).toBeVisible()
    await goal.getByRole('button').click()
    await expect(goal).toContainText('Token budget: 5,000')
    await expect(goal.getByRole('button')).toHaveCount(1)
    await expect(plan.getByRole('button')).toHaveAttribute('aria-expanded', 'false')
    const shot = testInfo.outputPath(`goal-${appearance}.png`)
    await page.screenshot({ path: shot })
    await testInfo.attach(`Goal ${appearance}`, { path: shot, contentType: 'image/png' })
    await plan.getByRole('button').click()
    await expect(goal.getByRole('button')).toHaveAttribute('aria-expanded', 'false')
    await expect(plan.getByRole('button')).toHaveAttribute('aria-expanded', 'true')
    await expect(send).toHaveAttribute('data-action', 'interrupt')
    await send.click()
    await expect(send).not.toHaveAttribute('data-action', 'interrupt')
    await expect(plan).toHaveCount(0)
    await expect(goal).toContainText('active')
    const summary = page.getByTestId('code-agent-transcript-process-summary').first()
    await expect(summary).toContainText('Interrupted')
    await expect(summary).toHaveAttribute('aria-expanded', 'false')
    await summary.click()
    const group = page.getByTestId('code-agent-transcript-process-group-toggle').first()
    await expect(group).toBeVisible()
    await group.click()
    await expect(page.locator('.code-agent-transcript-process-item[data-status="cancelled"]')).toContainText('Check service recovery')
    await expect(page.locator('.code-agent-transcript-process-item.status-running')).toHaveCount(0)
    await summary.click()
    const stoppedShot = testInfo.outputPath(`goal-interrupted-${appearance}.png`)
    await page.screenshot({ path: stoppedShot })
    await testInfo.attach(`Interrupted ${appearance}`, { path: stoppedShot, contentType: 'image/png' })
    const other = await create()
    await row(other).click()
    await expect(goal).toHaveCount(0)
    await row(id).click()
    await expect(goal).toBeVisible()
    await page.reload()
    await row(id).click()
    await expect(goal).toContainText('active')
    await input.fill('clear goal fixture')
    await send.click()
    await expect(page.getByText('Follow-up received; goal cleared.', { exact: true })).toBeVisible()
    await expect(goal).toHaveCount(0)
    await expect(summary).toContainText('Interrupted')
    await expect(summary).toHaveAttribute('aria-expanded', 'false')
  })
}

for (const appearance of ['light', 'dark', 'paper'] as const) {
  test(`completed Goals leave the dock and remain in Chat (${appearance})`, async ({ page, workspaceRoot }, testInfo) => {
    const workspace = path.join(workspaceRoot, 'goal-completion-demo')
    fs.mkdirSync(workspace, { recursive: true })
    const response = await page.request.post('/farming/api/control/agents', {
      data: { command: 'codex', workspace, agentRuntimeMode: 'chat' },
    })
    expect(response.ok()).toBeTruthy()
    const { agentId } = await response.json() as { agentId: string }
    await openFarming(page)
    await page.locator(`[data-testid="code-agent-row"][data-agent-id="${agentId}"]`).click()
    await page.locator('body').evaluate((body, value) => { body.dataset.appearance = value }, appearance)
    const input = page.getByTestId('code-acp-composer-input')
    const send = page.getByTestId('code-acp-composer-send')
    const goal = page.getByTestId('code-agent-goal-driver')
    const records = page.getByTestId('code-agent-goal-completion')
    const submit = async (text: string) => {
      await expect(send).not.toHaveAttribute('data-action', 'interrupt')
      await input.fill(text)
      await send.click()
    }
    for (const status of ['active', 'paused', 'blocked', 'budgetLimited', 'usageLimited']) {
      await submit(`goal status fixture ${status}`)
      await expect(goal).toContainText(status)
    }
    await goal.getByRole('button').click()
    await expect(goal.getByRole('button')).toHaveAttribute('aria-expanded', 'true')
    await submit('goal status fixture complete')
    await expect(goal).toContainText('complete')
    await expect(goal.getByRole('button')).toHaveAttribute('aria-expanded', 'false')
    await expect(records).toHaveCount(1)
    await expect(goal).toHaveCount(0, { timeout: 8000 })
    await records.getByRole('button').click()
    await expect(records).toContainText('Tokens used: 420')
    await expect(records).toContainText('Time used: 12 s')
    await page.screenshot({ path: testInfo.outputPath(`goal-completed-${appearance}.png`), animations: 'disabled' })
    await page.setViewportSize({ width: 390, height: 844 })
    await expect(records).toBeVisible()
    await page.screenshot({ path: testInfo.outputPath(`goal-completed-compact-${appearance}.png`), animations: 'disabled' })
    await page.setViewportSize({ width: 1280, height: 720 })
    await page.reload()
    await expect(records).toHaveCount(1)
    await expect(goal).toHaveCount(0)
    await submit('goal status fixture complete')
    await expect(page.getByText('Goal status is complete.', { exact: true })).toHaveCount(2)
    await expect(records).toHaveCount(1)
    await expect(goal).toHaveCount(0)
    await submit('clear goal fixture')
    await expect(page.getByText('Follow-up received; goal cleared.', { exact: true })).toBeVisible()
    await expect(records).toHaveCount(1)
    await submit('goal status fixture active 2')
    await expect(goal).toContainText('active')
    await submit('goal status fixture complete 2')
    await expect(goal).toContainText('complete')
    await expect(records).toHaveCount(2)
    await submit('goal status fixture active 3')
    await expect(goal).toContainText('active')
    await page.waitForTimeout(5100)
    await expect(goal).toContainText('active')
  })
}
