import fs from 'node:fs'
import path from 'node:path'
import { expect, openFarming, test } from './fixtures'

for (const mode of ['chat', 'terminal'] as const) {
  test(`${mode} attachment intake preserves mixed paste, previews, history and explicit errors`, async ({ page, workspaceRoot }, testInfo) => {
    const workspace = path.join(workspaceRoot, `attachment-intake-${mode}`)
    await page.addInitScript(() => localStorage.setItem('farming.composer-input-preferences', JSON.stringify({ foldLongPaste: false, optimizeImages: false })))
    fs.mkdirSync(workspace, { recursive: true })
    fs.writeFileSync(path.join(workspace, 'source.txt'), 'workspace context')
    await page.request.post('/farming/api/settings', { data: { language: 'en' } })
    const response = await page.request.post('/farming/api/control/agents', { data: { command: 'codex', workspace, agentRuntimeMode: mode } })
    expect(response.ok()).toBeTruthy()
    const { agentId } = await response.json() as { agentId: string }
    await openFarming(page)
    await page.locator(`[data-testid="code-agent-row"][data-agent-id="${agentId}"]`).click()
    const input = page.getByTestId(mode === 'chat' ? 'code-acp-composer-input' : 'code-composer-input')
    const send = page.getByTestId(mode === 'chat' ? 'code-acp-composer-send' : 'code-composer-send')
    await expect(input).toBeEditable()
    await input.fill('Review: ')
    await input.evaluate(element => {
      const transfer = new DataTransfer()
      transfer.items.add(new File(['# Document\n' + 'Complete source\n'.repeat(5000) + 'DOCUMENT_END'], 'review.md', { type: '' }))
      transfer.items.add(new File([Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII='), c => c.charCodeAt(0))], 'sample.png', { type: '' }))
      transfer.setData('text/plain', 'both files')
      element.dispatchEvent(new ClipboardEvent('paste', { clipboardData: transfer, bubbles: true, cancelable: true }))
    })
    await expect(input).toHaveValue('Review: both files')
    const card = page.getByTestId('code-composer-document')
    await expect(card).toHaveCount(1)
    await expect(card.getByRole('status')).toHaveCount(0)
    await card.locator('summary').click()
    await expect(card.locator('pre')).toContainText('DOCUMENT_END')
    const download = await page.request.get((await card.getByRole('link', { name: 'Download original' }).getAttribute('href'))!)
    expect(download.ok()).toBeTruthy(); expect(await download.text()).toContain('DOCUMENT_END')
    await card.locator('summary').click()
    const image = page.getByTestId('code-composer-attachment-preview')
    await expect(image).toHaveCount(1)
    await expect(page.locator('.code-composer-attachment.uploading')).toHaveCount(0)
    for (const [layout, viewport] of [['desktop', { width: 1440, height: 900 }], ['compact', { width: 390, height: 844 }]] as const) {
      await page.setViewportSize(viewport)
      for (const appearance of ['light', 'dark', 'paper']) {
        await page.evaluate(value => { document.body.dataset.appearance = value; document.documentElement.dataset.appearance = value }, appearance)
        await expect(send).toBeInViewport()
        await page.screenshot({ path: testInfo.outputPath(`${mode}-${layout}-${appearance}.png`), animations: 'disabled' })
        await image.click()
        const viewer = page.getByTestId('composer-image-viewer')
        await expect(viewer).toBeVisible()
        await expect(viewer.locator('img')).toHaveJSProperty('naturalWidth', 1)
        await page.screenshot({ path: testInfo.outputPath(`${mode}-${layout}-${appearance}-preview.png`), animations: 'disabled' })
        await page.keyboard.press('Escape')
        await expect(viewer).toHaveCount(0)
        await expect(image).toBeFocused()
      }
    }
    await page.setViewportSize({ width: 1440, height: 900 })
    await expect.poll(() => page.evaluate(() => localStorage.getItem('farming.code.agentComposerCheckpoint.v1'))).toContain('DOCUMENT_END')
    await page.reload()
    await expect(card).toHaveCount(1)
    await expect(image).toHaveCount(1)
    await image.click(); await expect(page.getByTestId('composer-image-viewer').locator('img')).toHaveJSProperty('naturalWidth', 1); await page.keyboard.press('Escape')
    await send.click()
    await expect(input).toHaveValue('')
    await expect(card).toHaveCount(0)
    if (mode === 'terminal' && await page.getByTestId('code-pending-followup-send-next').count()) await page.getByTestId('code-pending-followup-send-next').click()
    await input.press('ArrowUp')
    await expect(input).toHaveValue('Review: both files')
    await expect(card).toHaveCount(1)
    await expect(image).toHaveCount(1)
    await input.press('ArrowDown')
    await expect(input).toHaveValue('')
    await expect(card).toHaveCount(0)
    await input.evaluate(element => {
      const transfer = new DataTransfer(); transfer.items.add(new File([new Uint8Array([0, 1, 2])], 'unsupported.bin'))
      element.dispatchEvent(new DragEvent('drop', { dataTransfer: transfer, bubbles: true, cancelable: true }))
    })
    await expect(card.getByRole('alert')).toContainText('Unsupported binary')
    await page.getByRole('button', { name: 'Remove unsupported.bin', exact: true }).click()
    await expect(card).toHaveCount(0)
    const plus = page.getByTestId(mode === 'chat' ? 'code-acp-composer-add' : 'code-composer-add')
    await plus.click()
    const menu = page.getByTestId(mode === 'chat' ? 'code-acp-plus-menu' : 'code-composer-plus-menu')
    await expect(menu.getByRole('menuitemcheckbox')).toHaveCount(0)
    await expect(menu.getByRole('menuitem').first()).toContainText('Attach file')
    await expect(menu.getByRole('menuitem')).toHaveCount(3)
    for (const appearance of ['light', 'dark', 'paper']) {
      await page.evaluate(value => { document.body.dataset.appearance = value; document.documentElement.dataset.appearance = value }, appearance)
      await menu.screenshot({ path: testInfo.outputPath(`${mode}-commands-menu-${appearance}.png`), animations: 'disabled' })
    }
    await page.keyboard.press('Escape')
    const prevented = await input.evaluate(element => {
      const transfer = new DataTransfer(); transfer.setData('text/plain', 'long text\n'.repeat(150))
      return !element.dispatchEvent(new ClipboardEvent('paste', { clipboardData: transfer, bubbles: true, cancelable: true }))
    })
    expect(prevented).toBe(true)
    await expect(page.getByTestId('code-composer-pasted-text')).toHaveCount(1)
    await page.getByTestId('code-composer-pasted-text').getByRole('button', { name: 'Remove long text', exact: true }).click()
    await expect(page.getByTestId('code-composer-pasted-text')).toHaveCount(0)
    await page.locator('input[type="file"]').setInputFiles(path.resolve('tests/e2e/fixtures/composer-sample.heic'))
    await expect(page.locator('.code-composer-attachment.uploading')).toHaveCount(0)
    await expect(page.locator('.code-composer-attachment.error')).toHaveText([])
    await expect(image).toHaveCount(1)
    await image.click()
    await expect(page.getByTestId('composer-image-viewer').locator('img')).toHaveJSProperty('naturalWidth', 256)
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: /^Remove composer-sample\.(png|webp)$/ }).click()
    // An explicit global file paste returns to the last focused composer.
    await input.focus()
    await page.evaluate(() => {
      const transfer = new DataTransfer(); transfer.items.add(new File(['Global paste'], 'global.txt'))
      document.body.dispatchEvent(new ClipboardEvent('paste', { clipboardData: transfer, bubbles: true, cancelable: true }))
    })
    await expect(card).toContainText('global.txt')
    await expect(card.getByRole('status')).toHaveCount(0)
    await page.getByRole('button', { name: 'Remove global.txt', exact: true }).click()
    await input.evaluate(async element => {
      const canvas = document.createElement('canvas'); canvas.width = 3000; canvas.height = 1000
      const context = canvas.getContext('2d')!; context.fillStyle = '#2468ac'; context.fillRect(100, 100, 2800, 800)
      const blob = await new Promise<Blob>(resolve => canvas.toBlob(value => resolve(value!)))
      const transfer = new DataTransfer(); transfer.items.add(new File([blob], 'large.png', { type: 'image/png' }))
      element.dispatchEvent(new ClipboardEvent('paste', { clipboardData: transfer, bubbles: true, cancelable: true }))
    })
    await expect(image).toHaveCount(1)
    await expect(page.locator('.code-composer-attachment.uploading')).toHaveCount(0)
    await image.click()
    await expect(page.getByTestId('composer-image-viewer').locator('img')).toHaveJSProperty('naturalWidth', 2048)
    const alpha = await page.getByTestId('composer-image-viewer').locator('img').evaluate(element => {
      const image = element as HTMLImageElement
      const canvas = document.createElement('canvas'); canvas.width = image.naturalWidth; canvas.height = image.naturalHeight
      const context = canvas.getContext('2d')!; context.drawImage(image, 0, 0)
      return [context.getImageData(0, 0, 1, 1).data[3], context.getImageData(1000, 300, 1, 1).data[3]]
    })
    expect(alpha).toEqual([0, 255])
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: 'Remove large.webp', exact: true }).click()
    const originalBytes = await input.evaluate(async element => {
      const canvas = document.createElement('canvas'); canvas.width = 512; canvas.height = 512
      const context = canvas.getContext('2d')!; context.fillStyle = '#2468ac'; context.fillRect(0, 0, 512, 512)
      const blob = await new Promise<Blob>(resolve => canvas.toBlob(value => resolve(value!)))
      const transfer = new DataTransfer(); transfer.items.add(new File([blob], 'ordinary.png', { type: 'image/png' }))
      element.dispatchEvent(new ClipboardEvent('paste', { clipboardData: transfer, bubbles: true, cancelable: true }))
      return blob.size
    })
    await expect(image).toHaveCount(1)
    await expect(page.locator('.code-composer-attachment.uploading')).toHaveCount(0)
    await image.click()
    const optimizedImage = page.getByTestId('composer-image-viewer').locator('img')
    await expect(optimizedImage).toHaveJSProperty('naturalWidth', 512)
    const optimizedDownload = await page.request.get((await optimizedImage.getAttribute('src'))!)
    expect(optimizedDownload.ok()).toBeTruthy()
    expect((await optimizedDownload.body()).length).toBeLessThan(originalBytes)
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: 'Remove ordinary.webp', exact: true }).click()
    // Drag the actual file-tree row, retaining its authorized workspace identity.
    await page.locator('.code-files-title').click()
    const row = page.locator('[data-testid="code-file-row"][data-file-path="source.txt"]')
    await expect(row).toBeVisible()
    await row.dragTo(input)
    await expect(page.getByTestId('code-composer-context-chip')).toContainText('source.txt')

  })
}

test('side chat owns file uploads and mixed clipboard text independently', async ({ page, workspaceRoot }) => {
  const workspace = path.join(workspaceRoot, 'side-file-intake')
  fs.mkdirSync(workspace, { recursive: true })
  await page.request.post('/farming/api/settings', { data: { language: 'en' } })
  const response = await page.request.post('/farming/api/control/agents', { data: { command: 'codex', workspace, agentRuntimeMode: 'chat' } })
  const { agentId } = await response.json() as { agentId: string }
  await openFarming(page)
  await page.locator(`[data-testid="code-agent-row"][data-agent-id="${agentId}"]`).click()
  const parent = page.locator('.code-composer-shell').getByTestId('code-acp-composer-input')
  await parent.fill('image attachment parent context')
  await page.getByTestId('code-acp-composer-send').click()
  await expect(page.getByTestId('code-agent-chat-view')).toContainText('Received 0 image.')
  await parent.fill('/side')
  await page.getByTestId('code-acp-composer-send').click()
  const pane = page.getByTestId('code-subagent-panel')
  await expect(pane).toBeVisible()
  await parent.fill('Keep parent draft')
  const child = pane.getByTestId('code-acp-composer-input')
  await child.fill('Child: ')
  await child.evaluate(element => {
    const transfer = new DataTransfer(); transfer.items.add(new File(['Child document body'], 'child.md')); transfer.setData('text/plain', 'review this')
    element.dispatchEvent(new ClipboardEvent('paste', { clipboardData: transfer, bubbles: true, cancelable: true }))
  })
  await expect(child).toHaveValue('Child: review this')
  await expect(parent).toHaveValue('Keep parent draft')
  const card = pane.getByTestId('code-composer-document')
  await expect(card).toHaveCount(1)
  await expect(card.getByRole('status')).toHaveCount(0)
  await expect(page.locator('.code-composer-shell').getByTestId('code-composer-document')).toHaveCount(0)
  await pane.getByTestId('code-acp-composer-send').click()
  await expect(card).toHaveCount(0)
  await expect(pane.locator('.code-agent-transcript-user').last()).toContainText('Child document body')
  await expect(parent).toHaveValue('Keep parent draft')
  await child.press('ArrowUp')
  await expect(child).toHaveValue('Child: review this')
  await expect(card).toHaveCount(1)
})
