import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import postcss from 'postcss'

import { CODE_STYLE_SOURCES } from '../../src/styles/code-style-sources'

type AppearanceRegistry = Record<string, {
  css: Record<string, string>
  metadata: Record<string, string>
  mermaid: Record<string, string>
  monaco: Record<string, unknown>
  terminal: Record<string, string>
  terminalSearch: Record<string, string>
}>

const projectRoot = path.join(__dirname, '..', '..')
const tokenPath = 'src/styles/tokens.css'
const tokenSource = fs.readFileSync(path.join(projectRoot, tokenPath), 'utf8')
const tokenRoot = postcss.parse(tokenSource, { from: tokenPath })
const registry = JSON.parse(
  fs.readFileSync(path.join(projectRoot, 'shared/appearance-themes.json'), 'utf8'),
) as AppearanceRegistry
const appearances = ['light', 'dark', 'paper'] as const
const literalColor = /(?:#[\da-f]{3,8}\b|rgba?\(|hsla?\(|(?:^|[\s,:])(?:white|black)(?=$|[\s,;)]))/i
const extraAppearanceSources = [
  'src/components/CodeSelect.css',
  'src/styles/review.css',
  'extensions/browser/frontend/browser.css',
  'extensions/computer/frontend/computer.css',
] as const
const allAppearanceSources = [...CODE_STYLE_SOURCES, ...extraAppearanceSources]
const appearanceNeutralSources = new Set<string>(allAppearanceSources)
const fixedArtworkPaletteRoles = new Set([
  '--matrix-sol',
  '--matrix-terra',
  '--matrix-luna',
  '--matrix-ultra',
  '--matrix-danger',
  '--pet-black-hole-core',
  '--pet-black-hole-gold',
  '--pet-black-hole-gold-bright',
  '--pet-black-hole-gold-dark',
])
const runtimeCodeRoles = new Set([
  '--code-pet-status-glass-filter',
  '--code-sidebar-width',
])

function cssFilesBelow(relativeRoot: string): string[] {
  const absoluteRoot = path.join(projectRoot, relativeRoot)
  return fs.readdirSync(absoluteRoot, { withFileTypes: true }).flatMap(entry => {
    const relativePath = path.posix.join(relativeRoot, entry.name)
    if (entry.isDirectory()) return cssFilesBelow(relativePath)
    return entry.isFile() && entry.name.endsWith('.css') ? [relativePath] : []
  })
}

assert.deepEqual(Object.keys(registry).sort(), [...appearances].sort(), 'the registry must contain exactly the resolved appearances')
assert(tokenSource.startsWith('/* Generated by scripts/generate-code-appearance-css.ts. Do not edit. */'))
assert(!tokenSource.includes('--code-dark-'), 'appearance-specific compatibility aliases must not return')
assert(!tokenSource.includes('--code-paper-'), 'appearance names must not leak into semantic role names')
assert(!/--code-[\w-]+-[\da-f]{6}\b/i.test(tokenSource), 'mechanically hashed selector tokens must not return')
assert(!CODE_STYLE_SOURCES.some(source => source.endsWith('-dark.css')), 'dark component styles must not return')

const lightRoles = Object.keys(registry.light.css).sort()
assert(lightRoles.length <= 128, 'the semantic palette must not grow back into a selector-level override matrix')
for (const appearance of appearances) {
  const theme = registry[appearance]
  assert.deepEqual(Object.keys(theme.css).sort(), lightRoles, `${appearance} must define every CSS role`)
  for (const consumer of ['metadata', 'mermaid', 'monaco', 'terminal', 'terminalSearch'] as const) {
    assert(Object.keys(theme[consumer]).length > 0, `${appearance} must define its ${consumer} theme`)
  }

  const selector = appearance === 'light'
    ? 'body.code-mode'
    : `body.code-mode[data-appearance='${appearance}']`
  const rule = tokenRoot.nodes.find(node => node.type === 'rule' && node.selector === selector)
  assert(rule && rule.type === 'rule', `generated CSS must contain one ${appearance} rule`)
  const declarations = Object.fromEntries(
    (rule.nodes ?? [])
      .filter(node => node.type === 'decl' && node.prop.startsWith('--code-'))
      .map(declaration => [declaration.prop, declaration.value]),
  )
  assert.deepEqual(declarations, theme.css, `generated ${appearance} CSS must exactly match the registry`)
}
assert.equal(
  tokenRoot.nodes.filter(node => node.type === 'rule').length,
  appearances.length,
  'generated Code appearance CSS must contain only one rule per resolved appearance',
)

const bootstrapThemes = Object.fromEntries(appearances.map(appearance => [appearance, {
  canvas: registry[appearance].css['--code-bg-canvas'],
  colorScheme: registry[appearance].metadata.colorScheme,
  themeColor: registry[appearance].metadata.themeColor,
}]))
const indexSource = fs.readFileSync(path.join(projectRoot, 'index.html'), 'utf8')
assert(
  indexSource.includes(`const themes = ${JSON.stringify(bootstrapThemes)}`),
  'the first-paint bootstrap must be generated from the shared appearance registry',
)
assert(
  fs.readFileSync(path.join(projectRoot, 'backend/index-html.cts'), 'utf8')
    .includes("require('../shared/appearance-themes.json')"),
  'server-rendered browser metadata must consume the shared appearance registry',
)
for (const consumerPath of [
  'src/lib/theme.ts',
  'src/lib/workspace-editor-monaco.ts',
  'src/lib/xterm.ts',
  'src/components/files/FileEditorMarkdownPreview.tsx',
]) {
  const consumer = fs.readFileSync(path.join(projectRoot, consumerPath), 'utf8')
  assert(
    consumer.includes('appearanceTheme') || consumer.includes('APPEARANCE_THEMES'),
    `${consumerPath} must consume the shared appearance registry`,
  )
}

for (const sourcePath of allAppearanceSources) {
  const source = fs.readFileSync(path.join(projectRoot, sourcePath), 'utf8')
  const root = postcss.parse(source, { from: sourcePath })
  if (sourcePath === tokenPath || sourcePath === 'src/styles/crt-tokens.css') continue
  assert(!source.includes('data-appearance'), `${sourcePath} must stay appearance-neutral`)

  root.walkRules(rule => {
    if (!appearanceNeutralSources.has(sourcePath)) return
    rule.walkDecls(declaration => {
      const fixedArtworkPalette = fixedArtworkPaletteRoles.has(declaration.prop)
      const opaqueMaskAsset = declaration.prop === '--code-usage-day-shape'
      assert(
        fixedArtworkPalette || opaqueMaskAsset || !literalColor.test(declaration.value),
        `${sourcePath}:${declaration.source?.start?.line ?? '?'} must use a semantic color role for ${declaration.prop}`,
      )
    })
  })
}

const allCssSources = [...cssFilesBelow('src'), ...cssFilesBelow('extensions')]
const declaredCodeRoles = new Set(lightRoles)
for (const sourcePath of allCssSources) {
  const root = postcss.parse(fs.readFileSync(path.join(projectRoot, sourcePath), 'utf8'), { from: sourcePath })
  root.walkDecls(/^--code-/, declaration => declaredCodeRoles.add(declaration.prop))
}
for (const sourcePath of allCssSources) {
  const root = postcss.parse(fs.readFileSync(path.join(projectRoot, sourcePath), 'utf8'), { from: sourcePath })
  root.walkDecls(declaration => {
    const borderStyleKeywords = declaration.value.match(/\b(?:solid|dashed|dotted|double)\b/g) ?? []
    if (/^(?:border(?:-(?:top|right|bottom|left))?-color|outline-color)$/.test(declaration.prop)) {
      assert.equal(
        borderStyleKeywords.length,
        0,
        `${sourcePath}:${declaration.source?.start?.line ?? '?'} must not put a border style in ${declaration.prop}`,
      )
    }
    if (/^(?:border(?:-(?:top|right|bottom|left))?|outline)$/.test(declaration.prop)) {
      assert(
        borderStyleKeywords.length <= 1,
        `${sourcePath}:${declaration.source?.start?.line ?? '?'} repeats a border style in ${declaration.prop}`,
      )
    }
    for (const match of declaration.value.matchAll(/var\(\s*(--code-[\w-]+)([^)]*)\)/g)) {
      const [, role, tail] = match
      const hasFallback = tail.includes(',')
      assert(
        declaredCodeRoles.has(role) || runtimeCodeRoles.has(role) || hasFallback,
        `${sourcePath}:${declaration.source?.start?.line ?? '?'} references undefined ${role}`,
      )
    }
  })
}

console.log('test-code-appearance-css-contract passed')
