import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import postcss from 'postcss'

import { CODE_STYLE_SOURCES } from '../../src/styles/code-style-sources'

type AppearanceRegistry = Record<string, {
  css: Record<string, string>
  metadata: Record<string, string>
  mermaid: Record<string, string>
  monaco: Record<string, unknown>
  terminal: Record<string, string>
  terminalSearch: Record<string, string>
}>

const projectRoot = path.join(__dirname, '..', '..')
const tokenPath = 'src/styles/tokens.css'
const tokenSource = fs.readFileSync(path.join(projectRoot, tokenPath), 'utf8')
const tokenRoot = postcss.parse(tokenSource, { from: tokenPath })
const registry = JSON.parse(
  fs.readFileSync(path.join(projectRoot, 'shared/appearance-themes.json'), 'utf8'),
) as AppearanceRegistry
const appearances = ['light', 'dark', 'paper'] as const
const literalColor = /(?:#[\da-f]{3,8}\b|rgba?\(|hsla?\(|(?:^|[\s,:])(?:white|black)(?=$|[\s,;)]))/i
const extraAppearanceSources = [
  'src/components/CodeSelect.css',
  'src/styles/review.css',
  'extensions/browser/frontend/browser.css',
  'extensions/computer/frontend/computer.css',
] as const
const allAppearanceSources = [...CODE_STYLE_SOURCES, ...extraAppearanceSources]
const appearanceNeutralSources = new Set<string>(allAppearanceSources)
const fixedArtworkPaletteRoles = new Set([
  '--matrix-sol',
  '--matrix-terra',
  '--matrix-luna',
  '--matrix-ultra',
  '--matrix-danger',
  '--pet-black-hole-core',
  '--pet-black-hole-gold',
  '--pet-black-hole-gold-bright',
  '--pet-black-hole-gold-dark',
])
const runtimeCodeRoles = new Set([
  '--code-file-editor-tab-icon-source',
  '--code-pet-status-glass-filter',
  '--code-sidebar-width',
])

function cssFilesBelow(relativeRoot: string): string[] {
  const absoluteRoot = path.join(projectRoot, relativeRoot)
  return fs.readdirSync(absoluteRoot, { withFileTypes: true }).flatMap(entry => {
    const relativePath = path.posix.join(relativeRoot, entry.name)
    if (entry.isDirectory()) return cssFilesBelow(relativePath)
    return entry.isFile() && entry.name.endsWith('.css') ? [relativePath] : []
  })
}

assert.deepEqual(Object.keys(registry).sort(), [...appearances].sort(), 'the registry must contain exactly the resolved appearances')
assert(tokenSource.startsWith('/* Generated by scripts/generate-code-appearance-css.ts. Do not edit. */'))
assert(!tokenSource.includes('--code-dark-'), 'appearance-specific compatibility aliases must not return')
assert(!tokenSource.includes('--code-paper-'), 'appearance names must not leak into semantic role names')
assert(!/--code-[\w-]+-[\da-f]{6}\b/i.test(tokenSource), 'mechanically hashed selector tokens must not return')
assert(!CODE_STYLE_SOURCES.some(source => source.endsWith('-dark.css')), 'dark component styles must not return')

for (const appearance of appearances) {
  const roles = registry[appearance].css
  assert.match(roles['--code-active-item-surface'], /^#[0-9a-f]{6}$/i, `${appearance} active items must use an opaque final surface`)
  assert.equal(roles['--code-panel-border'], 'transparent', `${appearance} passive panels must use tonal separation`)
  assert.equal(roles['--code-panel-divider'], 'transparent', `${appearance} passive panel rows must use tonal separation`)
  assert.equal(roles['--code-composer-border'], 'transparent', `${appearance} composer must use tonal separation`)
}

assert.notEqual(
  registry.light.css['--code-bg-canvas'],
  registry.light.css['--code-bg-inset'],
  'light inset surfaces must remain distinct from the canvas',
)
assert.notEqual(
  registry.dark.css['--code-bg-canvas'],
  registry.dark.css['--code-bg-inset'],
  'dark inset surfaces must remain distinct from the canvas',
)

const lightRoles = Object.keys(registry.light.css).sort()
assert(lightRoles.length <= 132, 'the semantic palette must not grow back into a selector-level override matrix')
assert.equal(
  registry.light.css['--code-active-item-surface'],
  '#eeeeec',
  'light active items must remain neutral rather than use an accent-blue surface',
)
for (const appearance of appearances) {
  const theme = registry[appearance]
  assert.deepEqual(Object.keys(theme.css).sort(), lightRoles, `${appearance} must define every CSS role`)
  for (const consumer of ['metadata', 'mermaid', 'monaco', 'terminal', 'terminalSearch'] as const) {
    assert(Object.keys(theme[consumer]).length > 0, `${appearance} must define its ${consumer} theme`)
  }

  const selector = appearance === 'light'
    ? 'body.code-mode'
    : `body.code-mode[data-appearance='${appearance}']`
  const rule = tokenRoot.nodes.find(node => node.type === 'rule' && node.selector === selector)
  assert(rule && rule.type === 'rule', `generated CSS must contain one ${appearance} rule`)
  const declarations: Record<string, string> = {}
  rule.walkDecls(/^--code-/, declaration => {
    declarations[declaration.prop] = declaration.value
  })
  assert.deepEqual(declarations, theme.css, `generated ${appearance} CSS must exactly match the registry`)
}
assert.equal(
  tokenRoot.nodes.filter(node => node.type === 'rule').length,
  appearances.length,
  'generated Code appearance CSS must contain only one rule per resolved appearance',
)

const bootstrapThemes = Object.fromEntries(appearances.map(appearance => [appearance, {
  canvas: registry[appearance].css['--code-bg-canvas'],
  colorScheme: registry[appearance].metadata.colorScheme,
  themeColor: registry[appearance].metadata.themeColor,
}]))
const indexSource = fs.readFileSync(path.join(projectRoot, 'index.html'), 'utf8')
assert(
  indexSource.includes(`const themes = ${JSON.stringify(bootstrapThemes)}`),
  'the first-paint bootstrap must be generated from the shared appearance registry',
)
assert(
  fs.readFileSync(path.join(projectRoot, 'backend/index-html.cts'), 'utf8')
    .includes("require('../shared/appearance-themes.json')"),
  'server-rendered browser metadata must consume the shared appearance registry',
)
for (const consumerPath of [
  'src/lib/theme.ts',
  'src/lib/workspace-editor-monaco.ts',
  'src/lib/xterm.ts',
  'src/components/files/FileEditorMarkdownPreview.tsx',
]) {
  const consumer = fs.readFileSync(path.join(projectRoot, consumerPath), 'utf8')
  assert(
    consumer.includes('appearanceTheme') || consumer.includes('APPEARANCE_THEMES'),
    `${consumerPath} must consume the shared appearance registry`,
  )
}

for (const sourcePath of allAppearanceSources) {
  const source = fs.readFileSync(path.join(projectRoot, sourcePath), 'utf8')
  const root = postcss.parse(source, { from: sourcePath })
  if (sourcePath === tokenPath || sourcePath === 'src/styles/crt-tokens.css') continue
  assert(!source.includes('data-appearance'), `${sourcePath} must stay appearance-neutral`)

  root.walkRules(rule => {
    if (!appearanceNeutralSources.has(sourcePath)) return
    rule.walkDecls(declaration => {
      const fixedArtworkPalette = fixedArtworkPaletteRoles.has(declaration.prop)
      const opaqueMaskAsset = declaration.prop === '--code-usage-day-shape'
      assert(
        fixedArtworkPalette || opaqueMaskAsset || !literalColor.test(declaration.value),
        `${sourcePath}:${declaration.source?.start?.line ?? '?'} must use a semantic color role for ${declaration.prop}`,
      )
    })
  })
}

const allCssSources = [...cssFilesBelow('src'), ...cssFilesBelow('extensions')]
const declaredCodeRoles = new Set(lightRoles)
for (const sourcePath of allCssSources) {
  const root = postcss.parse(fs.readFileSync(path.join(projectRoot, sourcePath), 'utf8'), { from: sourcePath })
  root.walkDecls(/^--code-/, declaration => {
    declaredCodeRoles.add(declaration.prop)
  })
}
for (const sourcePath of allCssSources) {
  const root = postcss.parse(fs.readFileSync(path.join(projectRoot, sourcePath), 'utf8'), { from: sourcePath })
  root.walkDecls(declaration => {
    const borderStyleKeywords = declaration.value.match(/\b(?:solid|dashed|dotted|double)\b/g) ?? []
    if (/^(?:border(?:-(?:top|right|bottom|left))?-color|outline-color)$/.test(declaration.prop)) {
      assert.equal(
        borderStyleKeywords.length,
        0,
        `${sourcePath}:${declaration.source?.start?.line ?? '?'} must not put a border style in ${declaration.prop}`,
      )
    }
    if (/^(?:border(?:-(?:top|right|bottom|left))?|outline)$/.test(declaration.prop)) {
      assert(
        borderStyleKeywords.length <= 1,
        `${sourcePath}:${declaration.source?.start?.line ?? '?'} repeats a border style in ${declaration.prop}`,
      )
    }
    for (const match of declaration.value.matchAll(/var\(\s*(--code-[\w-]+)([^)]*)\)/g)) {
      const [, role, tail] = match
      const hasFallback = tail.includes(',')
      assert(
        declaredCodeRoles.has(role) || runtimeCodeRoles.has(role) || hasFallback,
        `${sourcePath}:${declaration.source?.start?.line ?? '?'} references undefined ${role}`,
      )
    }
  })
}

const semanticShadowContracts = [
  ['src/styles/markdown.css', '.code-agent-transcript-assistant.code-markdown-preview code', 'none'],
  ['src/styles/transcript.css', '.code-agent-transcript-process-item', 'none'],
  ['src/styles/transcript.css', '.code-agent-transcript-tool', 'none'],
  ['src/styles/transcript.css', '.code-agent-transcript-result', 'none'],
  ['src/styles/transcript.css', '.code-agent-transcript-plan-driver', 'none'],
  ['src/styles/transcript.css', '.code-agent-transcript-result-details', 'none'],
  ['src/styles/main.css', '.code-acp-request', 'none'],
  ['src/styles/main.css', '.code-pending-followup', 'none'],
  ['src/styles/main.css', '.workspace-history-item.active', 'none'],
  ['src/styles/files.css', '.code-file-blame-detail', 'none'],
  ['src/styles/files.css', '.code-file-line-changes-panel', 'none'],
  ['src/styles/composer.css', ".code-model-matrix-fast:not(.is-active)", 'none'],
] as const
for (const [sourcePath, selector, expectedShadow] of semanticShadowContracts) {
  const root = postcss.parse(fs.readFileSync(path.join(projectRoot, sourcePath), 'utf8'), { from: sourcePath })
  const matchingDeclarations = root.nodes.flatMap(node => (
    node.type === 'rule' && node.selector === selector ? node.nodes : []
  ))
  const shadow = matchingDeclarations
    .find(node => node.type === 'decl' && node.prop === 'box-shadow')
  assert(
    shadow?.type === 'decl' && shadow.value === expectedShadow,
    `${sourcePath} ${selector} must keep its in-flow content shadow at ${expectedShadow}`,
  )
}

const borderPurposeContracts = [
  ['src/styles/search.css', '.code-search-panel-input:focus-within', 'border-color', 'var(--code-focus-ring)'],
  ['src/styles/main.css', '.connection-status.lost,\n.connection-status.business-unavailable', 'border', '1px solid var(--code-border-danger)'],
  ['src/styles/transcript.css', '.code-agent-transcript-result-error', 'border', '1px solid var(--code-border-danger)'],
  ['src/styles/sidebar.css', '.code-sidebar-resizer', 'background', 'var(--code-border-subtle)'],
  ['src/styles/review.css', '.review-diff-columns span + span', 'border-left', '1px solid var(--code-border)'],
] as const
for (const [sourcePath, selector, property, expectedValue] of borderPurposeContracts) {
  const root = postcss.parse(fs.readFileSync(path.join(projectRoot, sourcePath), 'utf8'), { from: sourcePath })
  const rule = root.nodes.find(node => node.type === 'rule' && node.selector === selector)
  assert(rule && rule.type === 'rule', `${sourcePath} must retain the functional boundary for ${selector}`)
  const declaration = rule.nodes.find(node => node.type === 'decl' && node.prop === property)
  assert(
    declaration && declaration.type === 'decl' && declaration.value === expectedValue,
    `${sourcePath} must keep ${property}: ${expectedValue} for ${selector}`,
  )
}

const structuralSurfaceContracts = [
  ['src/styles/main.css', '.code-workspace', '--code-navigation-surface', 'var(--code-bg-chrome)'],
  ['src/styles/main.css', 'body.code-mode.code-compact-layout .code-workspace', '--code-navigation-surface', 'var(--code-panel-surface)'],
  ['src/styles/main.css', '.code-mobile-topbar', 'background', 'var(--code-navigation-surface)'],
  ['src/styles/main.css', 'body.code-mode.code-compact-layout .code-mobile-topbar-button', 'background', 'transparent'],
  ['src/styles/main.css', 'body.code-mode.code-compact-layout .code-mobile-topbar-button', 'box-shadow', 'none'],
  ['src/styles/sidebar.css', '.code-sidebar', 'background', 'var(--code-navigation-surface)'],
  ['src/styles/sidebar.css', '.code-project-row', 'background', 'linear-gradient(to bottom, var(--code-navigation-surface) 0 var(--code-project-sticky-height), transparent var(--code-project-sticky-height))'],
  ['src/styles/sidebar.css', '.code-sidebar-project-section', 'background', 'var(--code-navigation-surface)'],
  ['src/styles/sidebar.css', '.code-sidebar-options', 'background', 'transparent'],
  ['src/styles/sidebar.css', '.code-sidebar-toggle,\n.code-sidebar-focus-toggle,\n.code-sidebar-search-toggle,\n.code-sidebar-history-toggle,\n.code-sidebar-plugins-toggle', 'background', 'transparent'],
  ['src/styles/sidebar.css', '.code-sidebar-focus-toggle.active,\n.code-sidebar-search-toggle.active,\n.code-sidebar-history-toggle.active,\n.code-sidebar-plugins-toggle.active', 'background', 'var(--code-bg-selected)'],
  ['src/styles/share.css', '.code-share-button', 'background', 'transparent'],
  ['src/styles/files.css', '.code-open-editors-header,\n.code-files-header', 'background', 'var(--code-navigation-surface)'],
  ['src/styles/agent-list.css', '.code-agent-row', '--code-agent-row-action-surface', 'var(--code-navigation-surface)'],
  ['src/styles/agent-list.css', '.code-agent-row-actions', '--code-agent-row-action-surface', 'var(--code-navigation-surface)'],
  ['src/styles/agent-list.css', 'body.code-mode.code-compact-layout .code-agents-section', 'background', 'var(--code-navigation-surface)'],
  ['src/styles/agent-list.css', '.code-agent-row:hover', 'background', 'var(--code-active-item-surface)'],
  ['src/styles/agent-list.css', '.code-agent-row.active', 'background', 'var(--code-active-item-surface)'],
  ['src/styles/agent-list.css', '.code-agent-row.search-selected', 'background', 'var(--code-active-item-surface)'],
  ['src/styles/agent-list.css', '.code-agent-row', 'border-radius', '8px'],
  ['src/styles/agent-list.css', '.code-agent-row-actions', 'border-radius', '0 8px 8px 0'],
  ['src/styles/sidebar.css', '.code-project-title-actions', 'border-radius', '0 8px 8px 0'],
  ['src/styles/files.css', '.code-open-editor-row', 'border-radius', '8px'],
  ['src/styles/files.css', '.code-open-editor-main', 'border-radius', 'inherit'],
  ['src/styles/files.css', '.code-open-editor-actions', 'border-radius', '0 8px 8px 0'],
  ['src/styles/files.css', '.code-file-tree-row-frame', 'border-radius', '8px'],
  ['src/styles/files.css', '.code-file-row', 'border-radius', '8px'],
  ['src/styles/files.css', '.code-file-row:hover', 'background', 'var(--code-active-item-surface)'],
  ['src/styles/files.css', '.code-file-row.selected:not(.active)', 'background', 'var(--code-active-item-surface)'],
  ['src/styles/files.css', '.code-file-row.active', 'background', 'var(--code-active-item-surface)'],
  ['src/styles/files.css', 'body.code-mode.code-compact-layout .code-file-row.active', 'background', 'var(--code-active-item-surface)'],
  ['src/styles/files.css', 'body.code-mode.code-compact-layout .code-file-row', 'border-radius', '8px'],
  ['src/styles/file-editor.css', '.code-file-editor-tab:hover:not(.active)', 'background', 'var(--code-active-item-surface)'],
  ['src/styles/file-editor.css', '.code-file-editor-tab.active', 'background', 'var(--code-active-item-surface)'],
] as const
for (const [sourcePath, selector, property, expectedValue] of structuralSurfaceContracts) {
  const root = postcss.parse(fs.readFileSync(path.join(projectRoot, sourcePath), 'utf8'), { from: sourcePath })
  const values: string[] = []
  root.walkRules(rule => {
    if (rule.selector !== selector) return
    rule.walkDecls(property, declaration => {
      values.push(declaration.value)
    })
  })
  assert(values.length > 0, `${sourcePath} must declare ${property} for ${selector}`)
  assert(
    values.every(value => value === expectedValue),
    `${sourcePath} ${selector} must keep every ${property} declaration at ${expectedValue}; found ${values.join(', ')}`,
  )
}

const navigationSurfaceOwners = [
  '.code-mobile-topbar',
  '.code-sidebar',
  '.code-project-row',
  '.code-sidebar-project-section',
  '.code-agents-section',
  '.code-open-editors',
  '.code-open-editors-header',
  '.code-files-section',
  '.code-files-header',
]
for (const sourcePath of [
  'src/styles/main.css',
  'src/styles/sidebar.css',
  'src/styles/agent-list.css',
  'src/styles/files.css',
]) {
  const root = postcss.parse(fs.readFileSync(path.join(projectRoot, sourcePath), 'utf8'), { from: sourcePath })
  root.walkRules(rule => {
    const ownsNavigationSurface = rule.selector.split(',').some(selector => (
      navigationSurfaceOwners.some(owner => selector.trim().endsWith(owner))
    ))
    if (!ownsNavigationSurface) return
    rule.walkDecls(/^background(?:-color)?$/, declaration => {
      assert(
        !declaration.value.includes('var(--code-bg-chrome)')
          && !declaration.value.includes('var(--code-panel-surface)'),
        `${sourcePath} ${rule.selector} must consume --code-navigation-surface instead of selecting a layout-specific theme surface`,
      )
    })
  })
}

const semanticStateContracts = [
  ['src/styles/composer.css', '.code-composer-send:not(:disabled)', 'background', 'var(--code-emphasis)'],
  ['src/styles/composer.css', '.code-composer-send:not(:disabled)', 'color', 'var(--code-text-on-emphasis)'],
  ['src/styles/composer.css', '.code-composer-send:disabled', 'background', 'var(--code-bg-disabled)'],
  ['src/styles/composer.css', '.code-composer-send:disabled', 'color', 'var(--code-text-disabled)'],
  ['src/styles/composer.css', '.code-composer-send.interrupt', 'background', 'light-dark(var(--code-emphasis), var(--code-danger))'],
  ['src/styles/composer.css', '.code-composer-send.interrupt', 'color', 'var(--code-text-on-emphasis)'],
  ['src/styles/composer.css', '.code-composer-send.interrupt:not(:disabled):hover', 'background', 'light-dark(\n    var(--code-emphasis-hover),\n    color-mix(in srgb, var(--code-danger) 82%, var(--code-text))\n  )'],
  ['src/styles/main.css', '.kill-btn', 'color', 'var(--code-text-on-emphasis)'],
  ['src/styles/share.css', '.code-mobile-install-step', 'background', 'var(--code-bg-hover)'],
  ['src/styles/share.css', '.code-mobile-install-control', 'background', 'var(--code-bg-hover-strong)'],
  ['src/styles/file-editor.css', '.code-file-editor-action:hover:not(:disabled)', 'background', 'var(--code-bg-hover)'],
  ['src/styles/settings.css', '.code-settings-update-actions button.primary:hover:not(:disabled),\n.code-settings-update-actions button.primary:focus-visible', 'background', 'var(--code-accent-hover)'],
  ['src/styles/markdown.css', ".code-markdown-mermaid-toolbar button:hover:not(:disabled),\n.code-markdown-mermaid-toolbar button:focus-visible", 'background', 'var(--code-bg-hover)'],
] as const
for (const [sourcePath, selector, property, expectedValue] of semanticStateContracts) {
  const root = postcss.parse(fs.readFileSync(path.join(projectRoot, sourcePath), 'utf8'), { from: sourcePath })
  const declaration = root.nodes.flatMap(node => (
    node.type === 'rule' && node.selector === selector ? node.nodes : []
  )).find(node => node.type === 'decl' && node.prop === property)
  assert(
    declaration?.type === 'decl' && declaration.value === expectedValue,
    `${sourcePath} ${selector} must use ${expectedValue} for ${property}`,
  )
}

console.log('test-code-appearance-css-contract passed')
