import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import postcss from 'postcss'

import { CODE_STYLE_SOURCES } from '../../src/styles/code-style-sources'

type AppearanceRegistry = Record<string, {
  css: Record<string, string>
  metadata: Record<string, string>
  mermaid: Record<string, string>
  monaco: Record<string, unknown>
  terminal: Record<string, string>
  terminalSearch: Record<string, string>
}>

const projectRoot = path.join(__dirname, '..', '..')
const tokenPath = 'src/styles/tokens.css'
const scrollbarPath = 'src/styles/scrollbars.css'
const tokenSource = fs.readFileSync(path.join(projectRoot, tokenPath), 'utf8')
const tokenRoot = postcss.parse(tokenSource, { from: tokenPath })
const scrollbarSource = fs.readFileSync(path.join(projectRoot, scrollbarPath), 'utf8')
const scrollbarRoot = postcss.parse(scrollbarSource, { from: scrollbarPath })
const registry = JSON.parse(
  fs.readFileSync(path.join(projectRoot, 'shared/appearance-themes.json'), 'utf8'),
) as AppearanceRegistry
const appearances = ['light', 'dark', 'paper'] as const
const literalColor = /(?:#[\da-f]{3,8}\b|rgba?\(|hsla?\(|(?:^|[\s,:])(?:white|black)(?=$|[\s,;)]))/i
const extraAppearanceSources = [
  'src/components/CodeSelect.css',
  'src/styles/review.css',
  'extensions/browser/frontend/browser.css',
  'extensions/computer/frontend/computer.css',
] as const
const allAppearanceSources = [...CODE_STYLE_SOURCES, ...extraAppearanceSources]
const appearanceNeutralSources = new Set<string>(allAppearanceSources)
const fixedArtworkPaletteRoles = new Set([
  '--matrix-sol',
  '--matrix-terra',
  '--matrix-luna',
  '--matrix-ultra',
  '--matrix-danger',
  '--pet-black-hole-core',
  '--pet-black-hole-gold',
  '--pet-black-hole-gold-bright',
  '--pet-black-hole-gold-dark',
])
const runtimeCodeRoles = new Set([
  '--code-copy-toast-x',
  '--code-copy-toast-y',
  '--code-pet-status-glass-filter',
  '--code-sidebar-width',
])

function normalizedColor(value: string) {
  const hex = value.match(/^#([\da-f]{6})([\da-f]{2})?$/i)
  if (hex) {
    const rgb = hex[1]
    return [
      Number.parseInt(rgb.slice(0, 2), 16),
      Number.parseInt(rgb.slice(2, 4), 16),
      Number.parseInt(rgb.slice(4, 6), 16),
      hex[2] ? Number.parseInt(hex[2], 16) : 255,
    ]
  }
  const rgba = value.match(/^rgba?\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)(?:\s*,\s*([\d.]+))?\s*\)$/i)
  assert(rgba, `Unsupported contract color: ${value}`)
  return [
    Number(rgba[1]),
    Number(rgba[2]),
    Number(rgba[3]),
    Math.round(Number(rgba[4] ?? 1) * 255),
  ]
}

function cssFilesBelow(relativeRoot: string): string[] {
  const absoluteRoot = path.join(projectRoot, relativeRoot)
  return fs.readdirSync(absoluteRoot, { withFileTypes: true }).flatMap(entry => {
    const relativePath = path.posix.join(relativeRoot, entry.name)
    if (entry.isDirectory()) return cssFilesBelow(relativePath)
    return entry.isFile() && entry.name.endsWith('.css') ? [relativePath] : []
  })
}

assert.deepEqual(Object.keys(registry).sort(), [...appearances].sort(), 'the registry must contain exactly the resolved appearances')
assert(tokenSource.startsWith('/* Generated by scripts/generate-code-appearance-css.ts. Do not edit. */'))
assert(!tokenSource.includes('--code-dark-'), 'appearance-specific compatibility aliases must not return')
assert(!tokenSource.includes('--code-paper-'), 'appearance names must not leak into semantic role names')
assert(!/--code-[\w-]+-[\da-f]{6}\b/i.test(tokenSource), 'mechanically hashed selector tokens must not return')
assert(!CODE_STYLE_SOURCES.some(source => source.endsWith('-dark.css')), 'dark component styles must not return')

for (const appearance of appearances) {
  const roles = registry[appearance].css
  assert.match(roles['--code-active-item-surface'], /^#[0-9a-f]{6}$/i, `${appearance} active items must use an opaque final surface`)
  assert.equal(roles['--code-panel-border'], 'transparent', `${appearance} passive panels must use tonal separation`)
  assert.equal(roles['--code-panel-divider'], 'transparent', `${appearance} passive panel rows must use tonal separation`)
  assert.equal(roles['--code-composer-border'], 'transparent', `${appearance} composer must use tonal separation`)
  assert.notEqual(roles['--code-focus-ring'], 'transparent', `${appearance} non-text controls must have a visible keyboard-focus color`)
  for (const role of ['--code-shadow-focus', '--code-model-matrix-rocker-focus']) {
    assert.equal(roles[role], '0 0 0 1px var(--code-focus-ring)', `${appearance} ${role} must use one restrained control boundary, not layered rings`)
  }
}

assert.notEqual(
  registry.light.css['--code-bg-canvas'],
  registry.light.css['--code-bg-inset'],
  'light inset surfaces must remain distinct from the canvas',
)
assert.notEqual(
  registry.dark.css['--code-bg-canvas'],
  registry.dark.css['--code-bg-inset'],
  'dark inset surfaces must remain distinct from the canvas',
)

const lightRoles = Object.keys(registry.light.css).sort()
assert(lightRoles.length <= 136, 'the semantic palette must not grow back into a selector-level override matrix')
assert.equal(
  registry.light.css['--code-active-item-surface'],
  '#eeeeec',
  'light active items must remain neutral rather than use an accent-blue surface',
)
assert.equal(
  registry.light.css['--code-file-editor-active-tab-surface'],
  'var(--code-bg-canvas)',
  'light active editor tabs must connect to the document canvas',
)
assert.equal(
  registry.dark.css['--code-file-editor-active-tab-surface'],
  'var(--code-bg-canvas)',
  'dark active editor tabs must connect to the document canvas',
)
for (const appearance of ['light', 'dark'] as const) {
  assert.equal(
    registry[appearance].css['--code-file-editor-active-tab-seam'],
    'var(--code-file-editor-active-tab-surface)',
    `${appearance} active editor tabs must not expose a selected-blue seam`,
  )
}
const paperRoleContracts = {
  '--code-bg-canvas': '#f9f8f4',
  '--code-bg-chrome': '#f9f8f4',
  '--code-bg-inset': '#efede7',
  '--code-code-bg': '#efede7',
  '--code-active-item-surface': '#e6e5e1',
  '--code-file-editor-active-tab-surface': 'var(--code-active-item-surface)',
  '--code-file-editor-active-tab-seam': 'transparent',
  '--code-file-editor-tab-strip-surface': 'var(--code-bg-canvas)',
  '--code-composer-surface': 'var(--code-bg-raised)',
  '--code-info': '#397f79',
  '--code-success': '#3a6e4a',
  '--code-skill': '#6f4a8e',
  '--code-warning': '#8b5a18',
} as const
for (const [role, expectedValue] of Object.entries(paperRoleContracts)) {
  assert.equal(
    registry.paper.css[role],
    expectedValue,
    `Paper must keep ${role} at ${expectedValue}`,
  )
}
for (const appearance of appearances) {
  const theme = registry[appearance]
  assert.deepEqual(Object.keys(theme.css).sort(), lightRoles, `${appearance} must define every CSS role`)
  for (const consumer of ['metadata', 'mermaid', 'monaco', 'terminal', 'terminalSearch'] as const) {
    assert(Object.keys(theme[consumer]).length > 0, `${appearance} must define its ${consumer} theme`)
  }
  const monacoColors = theme.monaco.colors as Record<string, string>
  assert.deepEqual(
    normalizedColor(monacoColors['scrollbarSlider.background']),
    normalizedColor(theme.css['--code-scrollbar-thumb']),
    `${appearance} Monaco scrollbar must share the native default color`,
  )
  assert.deepEqual(
    normalizedColor(monacoColors['scrollbarSlider.hoverBackground']),
    normalizedColor(theme.css['--code-scrollbar-thumb-hover']),
    `${appearance} Monaco scrollbar must share the native hover color`,
  )
  assert.deepEqual(
    normalizedColor(monacoColors['scrollbarSlider.activeBackground']),
    normalizedColor(theme.css['--code-scrollbar-thumb-active']),
    `${appearance} Monaco scrollbar must share the native active color`,
  )
  assert.equal(
    theme.terminal.scrollbarSliderBackground,
    theme.css['--code-scrollbar-thumb'],
    `${appearance} Terminal scrollbar must share the native default color`,
  )
  assert.equal(
    theme.terminal.scrollbarSliderHoverBackground,
    theme.css['--code-scrollbar-thumb-hover'],
    `${appearance} Terminal scrollbar must share the native hover color`,
  )
  assert.equal(
    theme.terminal.scrollbarSliderActiveBackground,
    theme.css['--code-scrollbar-thumb-active'],
    `${appearance} Terminal scrollbar must share the native active color`,
  )

  const selector = appearance === 'light'
    ? 'body.code-mode'
    : `body.code-mode[data-appearance='${appearance}']`
  const rule = tokenRoot.nodes.find(node => node.type === 'rule' && node.selector === selector)
  assert(rule && rule.type === 'rule', `generated CSS must contain one ${appearance} rule`)
  const declarations: Record<string, string> = {}
  rule.walkDecls(/^--code-/, declaration => {
    declarations[declaration.prop] = declaration.value
  })
  assert.deepEqual(declarations, theme.css, `generated ${appearance} CSS must exactly match the registry`)
}

function scrollbarRule(selector: string) {
  const rule = scrollbarRoot.nodes.find(node => (
    node.type === 'rule' && node.selectors.includes(selector)
  ))
  assert(rule && rule.type === 'rule', `scrollbar stylesheet must define ${selector}`)
  return Object.fromEntries(rule.nodes
    .filter(node => node.type === 'decl')
    .map(declaration => [declaration.prop, declaration.value]))
}

assert.deepEqual(scrollbarRule('body.code-mode *'), {
  'scrollbar-color': 'transparent transparent',
  'scrollbar-width': 'thin',
})
assert.equal(
  scrollbarRule('body.code-mode *:hover')['scrollbar-color'],
  'var(--code-scrollbar-thumb) transparent',
)
assert.deepEqual(scrollbarRule('body.code-mode *::-webkit-scrollbar'), {
  width: '8px',
  height: '8px',
})
assert.deepEqual(scrollbarRule('body.code-mode *::-webkit-scrollbar-track'), {
  background: 'transparent',
})
assert.deepEqual(scrollbarRule('body.code-mode *::-webkit-scrollbar-thumb'), {
  border: '2px solid transparent',
  'border-radius': '999px',
  background: 'transparent',
  'background-clip': 'content-box',
})
assert.equal(
  scrollbarRule('body.code-mode *:hover::-webkit-scrollbar-thumb').background,
  'var(--code-scrollbar-thumb)',
)
assert.equal(
  scrollbarRule('body.code-mode *::-webkit-scrollbar-thumb:hover').background,
  'var(--code-scrollbar-thumb-hover)',
)
assert.equal(
  scrollbarRule('body.code-mode *::-webkit-scrollbar-thumb:active').background,
  'var(--code-scrollbar-thumb-active)',
)
assert.deepEqual(scrollbarRule('body.code-mode .monaco-scrollable-element > .scrollbar > .slider'), {
  'box-sizing': 'border-box',
  border: '2px solid transparent',
  'border-radius': '999px',
  'background-clip': 'content-box',
})

for (const sourcePath of allAppearanceSources) {
  if (sourcePath === scrollbarPath || sourcePath === tokenPath || sourcePath === 'src/styles/crt-tokens.css') continue
  const root = postcss.parse(fs.readFileSync(path.join(projectRoot, sourcePath), 'utf8'), { from: sourcePath })
  root.walkRules(rule => {
    rule.walkDecls(declaration => {
      const hiddenEditorTabs = sourcePath === 'src/styles/file-editor.css'
        && rule.selector === '.code-file-editor-tabs'
        && declaration.prop === 'scrollbar-width'
        && declaration.value === 'none'
      const hiddenEditorTabsPseudo = sourcePath === 'src/styles/file-editor.css'
        && rule.selector === '.code-file-editor-tabs::-webkit-scrollbar'
        && declaration.prop === 'display'
        && declaration.value === 'none'
      assert(
        hiddenEditorTabs
          || hiddenEditorTabsPseudo
          || (declaration.prop !== 'scrollbar-width'
            && declaration.prop !== 'scrollbar-color'
            && !rule.selector.includes('::-webkit-scrollbar')),
        `${sourcePath}:${declaration.source?.start?.line ?? '?'} must not override the shared Code scrollbar contract`,
      )
    })
  })
}
assert.equal(
  tokenRoot.nodes.filter(node => node.type === 'rule').length,
  appearances.length,
  'generated Code appearance CSS must contain only one rule per resolved appearance',
)

const bootstrapThemes = Object.fromEntries(appearances.map(appearance => [appearance, {
  canvas: registry[appearance].css['--code-bg-canvas'],
  colorScheme: registry[appearance].metadata.colorScheme,
  themeColor: registry[appearance].metadata.themeColor,
}]))
const indexSource = fs.readFileSync(path.join(projectRoot, 'index.html'), 'utf8')
assert(
  indexSource.includes(`const themes = ${JSON.stringify(bootstrapThemes)}`),
  'the first-paint bootstrap must be generated from the shared appearance registry',
)
assert(
  fs.readFileSync(path.join(projectRoot, 'backend/index-html.cts'), 'utf8')
    .includes("require('../shared/appearance-themes.json')"),
  'server-rendered browser metadata must consume the shared appearance registry',
)
for (const consumerPath of [
  'src/lib/theme.ts',
  'src/lib/workspace-editor-monaco.ts',
  'src/lib/xterm.ts',
  'src/components/files/FileEditorMarkdownPreview.tsx',
]) {
  const consumer = fs.readFileSync(path.join(projectRoot, consumerPath), 'utf8')
  assert(
    consumer.includes('appearanceTheme') || consumer.includes('APPEARANCE_THEMES'),
    `${consumerPath} must consume the shared appearance registry`,
  )
}

for (const sourcePath of allAppearanceSources) {
  const source = fs.readFileSync(path.join(projectRoot, sourcePath), 'utf8')
  const root = postcss.parse(source, { from: sourcePath })
  if (sourcePath === tokenPath || sourcePath === 'src/styles/crt-tokens.css') continue
  assert(!source.includes('data-appearance'), `${sourcePath} must stay appearance-neutral`)

  root.walkRules(rule => {
    if (!appearanceNeutralSources.has(sourcePath)) return
    rule.walkDecls(declaration => {
      const fixedArtworkPalette = fixedArtworkPaletteRoles.has(declaration.prop)
      const opaqueMaskAsset = declaration.prop === '--code-usage-day-shape'
      assert(
        fixedArtworkPalette || opaqueMaskAsset || !literalColor.test(declaration.value),
        `${sourcePath}:${declaration.source?.start?.line ?? '?'} must use a semantic color role for ${declaration.prop}`,
      )
    })
  })
}

const allCssSources = [...cssFilesBelow('src'), ...cssFilesBelow('extensions')]
const declaredCodeRoles = new Set(lightRoles)
for (const sourcePath of allCssSources) {
  const root = postcss.parse(fs.readFileSync(path.join(projectRoot, sourcePath), 'utf8'), { from: sourcePath })
  root.walkDecls(/^--code-/, declaration => {
    declaredCodeRoles.add(declaration.prop)
  })
}
for (const sourcePath of allCssSources) {
  const root = postcss.parse(fs.readFileSync(path.join(projectRoot, sourcePath), 'utf8'), { from: sourcePath })
  root.walkDecls(declaration => {
    const borderStyleKeywords = declaration.value.match(/\b(?:solid|dashed|dotted|double)\b/g) ?? []
    if (/^(?:border(?:-(?:top|right|bottom|left))?-color|outline-color)$/.test(declaration.prop)) {
      assert.equal(
        borderStyleKeywords.length,
        0,
        `${sourcePath}:${declaration.source?.start?.line ?? '?'} must not put a border style in ${declaration.prop}`,
      )
    }
    if (/^(?:border(?:-(?:top|right|bottom|left))?|outline)$/.test(declaration.prop)) {
      assert(
        borderStyleKeywords.length <= 1,
        `${sourcePath}:${declaration.source?.start?.line ?? '?'} repeats a border style in ${declaration.prop}`,
      )
    }
    for (const match of declaration.value.matchAll(/var\(\s*(--code-[\w-]+)([^)]*)\)/g)) {
      const [, role, tail] = match
      const hasFallback = tail.includes(',')
      assert(
        declaredCodeRoles.has(role) || runtimeCodeRoles.has(role) || hasFallback,
        `${sourcePath}:${declaration.source?.start?.line ?? '?'} references undefined ${role}`,
      )
    }
  })
}

// Keyboard-focus visibility is a behavior, not a requirement to frame every
// control. Text fields already expose the caret; reject focus-token leakage
// into their borders, outlines, and shadows at the owning stylesheet.
for (const sourcePath of allAppearanceSources) {
  const root = postcss.parse(fs.readFileSync(path.join(projectRoot, sourcePath), 'utf8'), { from: sourcePath })
  root.walkRules(rule => {
    const textField = /(?:^|[\s,(])(?:input|textarea)\b/.test(rule.selector)
      || /\.code-(?:search-panel-input|file-search-box):focus-within/.test(rule.selector)
    if (!textField) return
    const focusRule = /:focus(?:-visible|-within)?\b/.test(rule.selector)
    rule.walkDecls(declaration => {
      // The shared outline-color rule also lists buttons and does not draw an
      // outline by itself. Actual text-field outline geometry is checked below.
      if (declaration.prop === 'outline-color') return
      if (/^(?:border|outline|box-shadow)/.test(declaration.prop)) {
        assert(!/var\(--code-(?:focus-ring|shadow-focus)\)/.test(declaration.value),
          `${sourcePath} ${rule.selector} must not decorate text focus with ${declaration.prop}`)
      }
      if (focusRule && declaration.prop === 'box-shadow') {
        assert.equal(declaration.value, 'none', `${sourcePath} ${rule.selector} must not shadow text focus`)
      }
      if (focusRule && declaration.prop === 'outline') {
        assert(/^(?:0|none)$/.test(declaration.value), `${sourcePath} ${rule.selector} must use the text caret instead of an outline`)
      }
    })
  })
}

const semanticShadowContracts = [
  ['src/styles/markdown.css', '.code-agent-transcript-assistant.code-markdown-preview code', 'none'],
  ['src/styles/transcript.css', '.code-agent-transcript-process-item', 'none'],
  ['src/styles/transcript.css', '.code-agent-transcript-tool', 'none'],
  ['src/styles/transcript.css', '.code-agent-transcript-result', 'none'],
  ['src/styles/transcript.css', '.code-agent-transcript-plan-driver', 'none'],
  ['src/styles/transcript.css', '.code-agent-transcript-result-details', 'none'],
  ['src/styles/main.css', '.code-acp-request', 'none'],
  ['src/styles/main.css', '.code-pending-followup', 'none'],
  ['src/styles/main.css', '.workspace-history-item.active', 'none'],
  ['src/styles/files.css', '.code-file-blame-detail', 'none'],
  ['src/styles/files.css', '.code-file-line-changes-panel', 'none'],
  ['src/styles/composer.css', ".code-model-matrix-fast:not(.is-active)", 'none'],
  ['src/styles/search.css', '.code-search-panel-input:focus-within', 'none'],
] as const
for (const [sourcePath, selector, expectedShadow] of semanticShadowContracts) {
  const root = postcss.parse(fs.readFileSync(path.join(projectRoot, sourcePath), 'utf8'), { from: sourcePath })
  const matchingDeclarations = root.nodes.flatMap(node => (
    node.type === 'rule' && node.selector === selector ? node.nodes : []
  ))
  const shadow = matchingDeclarations
    .find(node => node.type === 'decl' && node.prop === 'box-shadow')
  assert(
    shadow?.type === 'decl' && shadow.value === expectedShadow,
    `${sourcePath} ${selector} must keep its in-flow content shadow at ${expectedShadow}`,
  )
}

const borderPurposeContracts = [
  ['src/styles/search.css', '.code-search-panel-input:focus-within', 'border-color', 'transparent'],
  ['src/styles/main.css', '.connection-status.lost,\n.connection-status.business-unavailable', 'border', '1px solid var(--code-border-danger)'],
  ['src/styles/transcript.css', '.code-agent-transcript-result-error', 'border', '1px solid var(--code-border-danger)'],
  ['src/styles/sidebar.css', '.code-sidebar-resizer', 'background', 'var(--code-border-subtle)'],
  ['src/styles/review.css', '.review-diff-columns span + span', 'border-left', '1px solid var(--code-border)'],
] as const
for (const [sourcePath, selector, property, expectedValue] of borderPurposeContracts) {
  const root = postcss.parse(fs.readFileSync(path.join(projectRoot, sourcePath), 'utf8'), { from: sourcePath })
  const rule = root.nodes.find(node => node.type === 'rule' && node.selector === selector)
  assert(rule && rule.type === 'rule', `${sourcePath} must retain the functional boundary for ${selector}`)
  const declaration = rule.nodes.find(node => node.type === 'decl' && node.prop === property)
  assert(
    declaration && declaration.type === 'decl' && declaration.value === expectedValue,
    `${sourcePath} must keep ${property}: ${expectedValue} for ${selector}`,
  )
}

const structuralSurfaceContracts = [
  ['src/styles/main.css', '.code-workspace', '--code-navigation-surface', 'var(--code-bg-chrome)'],
  ['src/styles/main.css', 'body.code-mode.code-compact-layout .code-workspace', '--code-navigation-surface', 'var(--code-panel-surface)'],
  ['src/styles/main.css', '.code-mobile-topbar', 'background', 'var(--code-navigation-surface)'],
  ['src/styles/main.css', 'body.code-mode.code-compact-layout .code-mobile-topbar-button', 'background', 'transparent'],
  ['src/styles/main.css', 'body.code-mode.code-compact-layout .code-mobile-topbar-button', 'box-shadow', 'none'],
  ['src/styles/sidebar.css', '.code-sidebar', 'background', 'var(--code-navigation-surface)'],
  ['src/styles/sidebar.css', '.code-project-row', 'background', 'linear-gradient(to bottom, var(--code-navigation-surface) 0 var(--code-project-sticky-height), transparent var(--code-project-sticky-height))'],
  ['src/styles/sidebar.css', '.code-sidebar-project-section', 'background', 'var(--code-navigation-surface)'],
  ['src/styles/sidebar.css', '.code-sidebar-options', 'background', 'transparent'],
  ['src/styles/sidebar.css', '.code-sidebar-toggle,\n.code-sidebar-focus-toggle,\n.code-sidebar-search-toggle,\n.code-sidebar-history-toggle,\n.code-sidebar-plugins-toggle', 'background', 'transparent'],
  ['src/styles/sidebar.css', '.code-sidebar-focus-toggle.active,\n.code-sidebar-search-toggle.active,\n.code-sidebar-history-toggle.active,\n.code-sidebar-plugins-toggle.active', 'background', 'var(--code-bg-selected)'],
  ['src/styles/share.css', '.code-share-button', 'background', 'transparent'],
  ['src/styles/files.css', '.code-open-editors-header,\n.code-files-header', 'background', 'var(--code-navigation-surface)'],
  ['src/styles/agent-list.css', '.code-agent-row', '--code-agent-row-surface', 'var(--code-navigation-surface)'],
  ['src/styles/agent-list.css', '.code-agent-row-actions', 'background', 'linear-gradient(90deg, transparent 0, var(--code-agent-row-surface) 21px)'],
  ['src/styles/agent-list.css', 'body.code-mode.code-compact-layout .code-agents-section', 'background', 'var(--code-navigation-surface)'],
  ['src/styles/agent-list.css', '.code-agents-section', 'border-radius', '0'],
  ['src/styles/agent-list.css', '.code-agent-row:hover', 'background', 'var(--code-active-item-surface)'],
  ['src/styles/agent-list.css', '.code-agent-row.active', 'background', 'var(--code-active-item-surface)'],
  ['src/styles/agent-list.css', '.code-agent-row.search-selected', 'background', 'var(--code-active-item-surface)'],
  ['src/styles/agent-list.css', '.code-agent-row', 'border-radius', '8px'],
  ['src/styles/sidebar.css', '.code-project-title-actions', 'border-radius', '0 8px 8px 0'],
  ['src/styles/files.css', '.code-open-editor-row', 'border-radius', '8px'],
  ['src/styles/files.css', '.code-open-editors', 'border-radius', '0'],
  ['src/styles/files.css', '.code-open-editors', 'margin-left', '0'],
  ['src/styles/files.css', '.code-open-editors', 'padding-left', '14px'],
  ['src/styles/files.css', '.code-files-header', 'margin-left', '-14px'],
  ['src/styles/files.css', '.code-files-header', 'padding-left', '14px'],
  ['src/styles/files.css', '.code-open-editor-main', 'border-radius', 'inherit'],
  ['src/styles/files.css', '.code-open-editor-actions', 'border-radius', '0 8px 8px 0'],
  ['src/styles/files.css', '.code-file-tree-row-frame', 'border-radius', '8px'],
  ['src/styles/files.css', '.code-file-tree-row-frame', 'background', 'transparent'],
  ['src/styles/files.css', '.code-file-tree-row-frame', 'overflow', 'hidden'],
  ['src/styles/files.css', '.code-file-tree-row-frame:hover', 'background', 'var(--code-active-item-surface)'],
  ['src/styles/files.css', '.code-file-tree-row-frame.active,\n.code-file-tree-row-frame:has(.code-file-row.active)', 'background', 'var(--code-active-item-surface)'],
  ['src/styles/files.css', '.code-file-tree-viewport:focus-within .code-file-tree-row-frame:has(.code-file-row.selected:not(.active))', 'background', 'var(--code-active-item-surface)'],
  ['src/styles/files.css', '.code-file-row', 'border-radius', '8px'],
  ['src/styles/files.css', '.code-file-row', 'background', 'transparent'],
  ['src/styles/files.css', 'body.code-mode.code-compact-layout .code-file-row', 'border-radius', '8px'],
  ['src/styles/file-editor.css', '.code-file-editor-tab:hover:not(.active)', 'background', 'var(--code-file-editor-active-tab-surface)'],
  ['src/styles/file-editor.css', '.code-file-editor-tab.active', 'background', 'var(--code-file-editor-active-tab-surface)'],
] as const
for (const [sourcePath, selector, property, expectedValue] of structuralSurfaceContracts) {
  const root = postcss.parse(fs.readFileSync(path.join(projectRoot, sourcePath), 'utf8'), { from: sourcePath })
  const values: string[] = []
  root.walkRules(rule => {
    if (rule.selector !== selector) return
    rule.walkDecls(property, declaration => {
      values.push(declaration.value)
    })
  })
  assert(values.length > 0, `${sourcePath} must declare ${property} for ${selector}`)
  assert(
    values.every(value => value === expectedValue),
    `${sourcePath} ${selector} must keep every ${property} declaration at ${expectedValue}; found ${values.join(', ')}`,
  )
}

const agentListSource = fs.readFileSync(path.join(projectRoot, 'src/styles/agent-list.css'), 'utf8')
assert(!agentListSource.includes('--code-agent-row-action-surface'), 'Agent actions must not own a second base surface')
assert(!agentListSource.includes('--code-agent-row-action-overlay'), 'Agent actions must not own a second state overlay')

const fileStylesRoot = postcss.parse(
  fs.readFileSync(path.join(projectRoot, 'src/styles/files.css'), 'utf8'),
  { from: 'src/styles/files.css' },
)
const fileContentStateSelectors = new Set([
  '.code-file-row:hover',
  '.code-file-row.focused',
  '.code-file-row.selected:not(.active)',
  '.code-file-row.opening:not(.active)',
  '.code-file-row.active',
])
fileStylesRoot.walkRules(rule => {
  if (!fileContentStateSelectors.has(rule.selector)) return
  assert(
    !rule.nodes.some(node => node.type === 'decl' && node.prop === 'background'),
    `${rule.selector} content must not own a state background`,
  )
})

const navigationSurfaceOwners = [
  '.code-mobile-topbar',
  '.code-sidebar',
  '.code-project-row',
  '.code-sidebar-project-section',
  '.code-agents-section',
  '.code-open-editors',
  '.code-open-editors-header',
  '.code-files-section',
  '.code-files-header',
]
for (const sourcePath of [
  'src/styles/main.css',
  'src/styles/sidebar.css',
  'src/styles/agent-list.css',
  'src/styles/files.css',
]) {
  const root = postcss.parse(fs.readFileSync(path.join(projectRoot, sourcePath), 'utf8'), { from: sourcePath })
  root.walkRules(rule => {
    const ownsNavigationSurface = rule.selector.split(',').some(selector => (
      navigationSurfaceOwners.some(owner => selector.trim().endsWith(owner))
    ))
    if (!ownsNavigationSurface) return
    rule.walkDecls(/^background(?:-color)?$/, declaration => {
      assert(
        !declaration.value.includes('var(--code-bg-chrome)')
          && !declaration.value.includes('var(--code-panel-surface)'),
        `${sourcePath} ${rule.selector} must consume --code-navigation-surface instead of selecting a layout-specific theme surface`,
      )
    })
  })
}

const semanticStateContracts = [
  ['src/styles/composer.css', '.code-composer-send:not(:disabled)', 'background', 'light-dark(var(--code-emphasis), var(--code-text-muted))'],
  ['src/styles/composer.css', '.code-composer-send:not(:disabled)', 'color', 'light-dark(var(--code-text-on-emphasis), var(--code-bg-canvas))'],
  ['src/styles/composer.css', '.code-composer-send:not(:disabled):hover', 'background', 'light-dark(var(--code-emphasis-hover), var(--code-text))'],
  ['src/styles/composer.css', '.code-composer-send:disabled', 'background', 'var(--code-bg-disabled)'],
  ['src/styles/composer.css', '.code-composer-send:disabled', 'color', 'var(--code-text-disabled)'],
  ['src/styles/composer.css', '.code-composer-send.interrupt', 'background', 'light-dark(var(--code-emphasis), var(--code-danger))'],
  ['src/styles/composer.css', '.code-composer-send.interrupt', 'color', 'var(--code-text-on-emphasis)'],
  ['src/styles/composer.css', '.code-composer-send.interrupt:not(:disabled):hover', 'background', 'light-dark(\n    var(--code-emphasis-hover),\n    color-mix(in srgb, var(--code-danger) 82%, var(--code-text))\n  )'],
  ['src/styles/markdown.css', '.code-agent-transcript-assistant.code-markdown-preview pre', 'background', 'var(--code-code-bg)'],
  ['src/styles/markdown.css', '.code-markdown-preview code', 'background', 'var(--code-code-bg)'],
  ['src/styles/markdown.css', '.code-markdown-preview tr:nth-child(2n)', 'background', 'var(--code-code-bg)'],
  ['src/styles/markdown.css', '.code-markdown-preview .hljs-keyword,\n.code-markdown-preview .hljs-selector-tag,\n.code-markdown-preview .hljs-subst', 'color', 'var(--code-syntax-keyword)'],
  ['src/styles/markdown.css', '.code-markdown-preview .hljs-doctag,\n.code-markdown-preview .hljs-string', 'color', 'var(--code-syntax-string)'],
  ['src/styles/transcript.css', '.code-agent-transcript-live-activity-icon.kind-running', 'color', 'var(--code-success)'],
  ['src/styles/transcript.css', '.code-agent-transcript-live-activity-icon.kind-reading,\n.code-agent-transcript-live-activity-icon.kind-searching', 'color', 'var(--code-info)'],
  ['src/styles/transcript.css', '.code-agent-transcript-live-activity-icon.kind-editing', 'color', 'var(--code-skill)'],
  ['src/styles/transcript.css', '.code-agent-transcript-file-link', 'background', 'light-dark(var(--code-code-bg), var(--code-accent-soft))'],
  ['src/styles/transcript.css', '.code-agent-transcript-file-link', 'color', 'var(--code-info)'],
  ['src/styles/review.css', '.review-commit-message', 'color', 'var(--code-text-muted)'],
  ['src/styles/review.css', '.review-commit-message summary > strong', 'color', 'var(--code-text)'],
  ['src/styles/sidebar.css', '.code-worktree-popover-status.success', 'color', 'var(--code-success)'],
  ['src/styles/usage.css', '.code-usage-heatmap-cell', 'background', 'color-mix(in srgb, var(--code-heatmap-level-1) 34%, transparent)'],
  ['src/styles/usage.css', ".code-usage-detail-day-highlight[data-state='selected'] > strong", 'color', 'var(--code-chart-line)'],
  ['src/styles/main.css', '.kill-btn', 'color', 'var(--code-text-on-emphasis)'],
  ['src/styles/share.css', '.code-mobile-install-step', 'background', 'var(--code-bg-hover)'],
  ['src/styles/share.css', '.code-mobile-install-control', 'background', 'var(--code-bg-hover-strong)'],
  ['src/styles/file-editor.css', '.code-file-editor-action:hover:not(:disabled)', 'background', 'var(--code-bg-hover)'],
  ['src/styles/settings.css', '.code-settings-update-actions button.primary:hover:not(:disabled),\n.code-settings-update-actions button.primary:focus-visible', 'background', 'var(--code-accent-hover)'],
  ['src/styles/markdown.css', ".code-markdown-mermaid-toolbar button:hover:not(:disabled),\n.code-markdown-mermaid-toolbar button:focus-visible", 'background', 'var(--code-bg-hover)'],
] as const
for (const [sourcePath, selector, property, expectedValue] of semanticStateContracts) {
  const root = postcss.parse(fs.readFileSync(path.join(projectRoot, sourcePath), 'utf8'), { from: sourcePath })
  const declaration = root.nodes.flatMap(node => (
    node.type === 'rule' && node.selector === selector ? node.nodes : []
  )).find(node => node.type === 'decl' && node.prop === property)
  assert(
    declaration?.type === 'decl' && declaration.value === expectedValue,
    `${sourcePath} ${selector} must use ${expectedValue} for ${property}`,
  )
}

console.log('test-code-appearance-css-contract passed')
