export const CODE_STYLE_SOURCES = [
  'src/styles/crt-tokens.css',
  'src/styles/tokens.css',
  'src/styles/main.css',
  'src/styles/file-editor.css',
  'src/styles/pet.css',
  'src/styles/git-history.css',
  'src/styles/composer.css',
  'src/styles/plugin.css',
  'src/styles/settings.css',
  'src/styles/share.css',
  'src/styles/sidebar-resources.css',
  'src/styles/usage.css',
  'src/styles/markdown.css',
  'src/styles/search.css',
  'src/styles/history.css',
  'src/styles/empty.css',
  'src/styles/language-server.css',
  'src/styles/desktop-backend.css',
  'src/styles/terminal.css',
  'src/styles/files.css',
  'src/styles/sidebar.css',
  'src/styles/transcript.css',
  'src/styles/agent-list.css',
] as const

export type CodeStyleSourcePath = typeof CODE_STYLE_SOURCES[number]
