// Generated by scripts/build-backend-runtime.ts. Do not edit.
"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var appearance_themes_exports = {};
__export(appearance_themes_exports, {
  APPEARANCE_THEMES: () => APPEARANCE_THEMES,
  RESOLVED_APPEARANCES: () => RESOLVED_APPEARANCES,
  appearanceTheme: () => appearanceTheme,
  isResolvedAppearance: () => isResolvedAppearance
});
module.exports = __toCommonJS(appearance_themes_exports);
var import_appearance_themes = __toESM(require("./appearance-themes.json"));
const RESOLVED_APPEARANCES = ["light", "dark", "paper"];
const APPEARANCE_THEMES = import_appearance_themes.default;
function isResolvedAppearance(value) {
  return typeof value === "string" && RESOLVED_APPEARANCES.includes(value);
}
function appearanceTheme(value) {
  return APPEARANCE_THEMES[isResolvedAppearance(value) ? value : "light"];
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  APPEARANCE_THEMES,
  RESOLVED_APPEARANCES,
  appearanceTheme,
  isResolvedAppearance
});
