#!/usr/bin/env -S npx tsx

import fs from 'node:fs';
import path from 'node:path';
import * as esbuild from 'esbuild';

const projectRoot = path.resolve(__dirname, '..');
const runtimeRoots = [
  path.join(projectRoot, 'backend'),
  path.join(projectRoot, 'extensions', 'browser', 'backend'),
  path.join(projectRoot, 'extensions', 'computer', 'backend'),
];
const sourceOnlyDirectories = new Set(['tests', 'types', 'vendor']);
const generatedHeader = '// Generated by scripts/build-backend-runtime.ts. Do not edit.';
const legacyGeneratedHeader = '// Generated by scripts/build-backend-runtime.js. Do not edit.';

function collectFiles(directory: string, extension: string): string[] {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const entryPath = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      return sourceOnlyDirectories.has(entry.name) ? [] : collectFiles(entryPath, extension);
    }
    return entry.isFile() && entry.name.endsWith(extension) ? [entryPath] : [];
  });
}

async function main(): Promise<void> {
  const entryPoints = runtimeRoots.flatMap(root => collectFiles(root, '.cts')).sort();
  if (entryPoints.length === 0) {
    throw new Error('No backend TypeScript runtime modules were found');
  }

  await esbuild.build({
    entryPoints,
    outdir: projectRoot,
    outbase: projectRoot,
    outExtension: { '.js': '.cjs' },
    bundle: false,
    platform: 'node',
    format: 'cjs',
    target: 'node22',
    legalComments: 'none',
    logLevel: 'warning',
    banner: { js: generatedHeader },
  });

  const expectedOutputs = new Set(entryPoints.map(
    sourcePath => sourcePath.slice(0, -'.cts'.length) + '.cjs',
  ));
  for (const runtimeRoot of runtimeRoots) {
    for (const filePath of collectFiles(runtimeRoot, '.cjs')) {
      if (expectedOutputs.has(filePath)) continue;
      const source = fs.readFileSync(filePath, 'utf8');
      if (source.startsWith(generatedHeader) || source.startsWith(legacyGeneratedHeader)) {
        fs.rmSync(filePath, { force: true });
      }
    }
  }
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
