#!/usr/bin/env -S npx tsx

import fs from 'node:fs'
import path from 'node:path'

import { APPEARANCE_THEMES, RESOLVED_APPEARANCES } from '../shared/appearance-themes'

const projectRoot = path.resolve(__dirname, '..')
const outputPath = path.join(projectRoot, 'src', 'styles', 'tokens.css')
const indexPath = path.join(projectRoot, 'index.html')
const generatedHeader = '/* Generated by scripts/generate-code-appearance-css.ts. Do not edit. */'
const bootstrapStart = '    <!-- appearance-bootstrap:start -->'
const bootstrapEnd = '    <!-- appearance-bootstrap:end -->'
const lightProperties = Object.keys(APPEARANCE_THEMES.light.css).sort()

for (const appearance of RESOLVED_APPEARANCES) {
  const properties = Object.keys(APPEARANCE_THEMES[appearance].css).sort()
  if (properties.length !== lightProperties.length || properties.some((property, index) => property !== lightProperties[index])) {
    throw new Error(`${appearance} CSS palette must define exactly the same semantic roles as Light`)
  }
}

function renderAppearance(appearance: typeof RESOLVED_APPEARANCES[number]) {
  const theme = APPEARANCE_THEMES[appearance]
  const selector = appearance === 'light'
    ? 'body.code-mode'
    : `body.code-mode[data-appearance='${appearance}']`
  const declarations = lightProperties.map(property => `  ${property}: ${theme.css[property]};`)
  return [
    `${selector} {`,
    `  color-scheme: ${theme.metadata.colorScheme};`,
    ...declarations,
    '}',
  ].join('\n')
}

const output = `${generatedHeader}\n\n${RESOLVED_APPEARANCES.map(renderAppearance).join('\n\n')}\n`
fs.writeFileSync(outputPath, output)

const bootstrapThemes = Object.fromEntries(RESOLVED_APPEARANCES.map(appearance => {
  const theme = APPEARANCE_THEMES[appearance]
  return [appearance, {
    canvas: theme.css['--code-bg-canvas'],
    colorScheme: theme.metadata.colorScheme,
    themeColor: theme.metadata.themeColor,
  }]
}))
const bootstrap = `${bootstrapStart}
    <style id="farming-appearance-bootstrap-style">
      html,
      body {
        background: ${bootstrapThemes.light.canvas};
      }

      html[data-appearance='dark'],
      html[data-appearance='dark'] body {
        background: ${bootstrapThemes.dark.canvas};
        color-scheme: ${bootstrapThemes.dark.colorScheme};
      }

      html[data-appearance='paper'],
      html[data-appearance='paper'] body {
        background: ${bootstrapThemes.paper.canvas};
        color-scheme: ${bootstrapThemes.paper.colorScheme};
      }
    </style>
    <script>
      (() => {
        const themes = ${JSON.stringify(bootstrapThemes)}
        const root = document.documentElement
        const preference = Object.hasOwn(themes, root.dataset.appearancePreference)
          ? root.dataset.appearancePreference
          : 'system'
        const appearance = preference === 'system'
          ? (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light')
          : preference
        const theme = themes[appearance]
        root.dataset.appearance = appearance
        document.querySelector('meta[name="color-scheme"]')?.setAttribute('content', theme.colorScheme)
        document.querySelector('meta[name="theme-color"]')?.setAttribute('content', theme.themeColor)
      })()
    </script>
${bootstrapEnd}`
const indexSource = fs.readFileSync(indexPath, 'utf8')
const startIndex = indexSource.indexOf(bootstrapStart)
const endIndex = indexSource.indexOf(bootstrapEnd)
if (startIndex < 0 || endIndex < startIndex) throw new Error('index.html appearance bootstrap markers are missing')
const nextIndex = `${indexSource.slice(0, startIndex)}${bootstrap}${indexSource.slice(endIndex + bootstrapEnd.length)}`
fs.writeFileSync(indexPath, nextIndex)
