// Generated by scripts/build-backend-runtime.ts. Do not edit.
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var computer_router_exports = {};
__export(computer_router_exports, {
  createComputerRouter: () => createComputerRouter
});
module.exports = __toCommonJS(computer_router_exports);
const express = require("express");
const http = require("http");
function recordValue(value) {
  return value && typeof value === "object" && !Array.isArray(value) ? value : {};
}
function requestAgentId(req) {
  return String(req.get?.("X-Farming-Agent-Id") || "").trim();
}
function ownerAgent(agentStateReader, agentId) {
  const agents = agentStateReader?.getState()?.agents;
  return Array.isArray(agents) ? agents.map(recordValue).find((agent) => agent.id === agentId) : void 0;
}
function assertRequestOwner(manager, req, id) {
  const agentId = requestAgentId(req);
  if (!agentId) return;
  const resource = manager.get(id);
  if (resource.ownerAgentId !== agentId) {
    throw Object.assign(new Error("Computer Resource is not owned by this Agent"), {
      status: 403,
      code: "COMPUTER_OWNER_MISMATCH"
    });
  }
}
function sendError(res, caught) {
  const error = caught;
  res.status(Number(error.status) || 500).json({
    error: error.message || "Computer request failed",
    ...error.code ? { code: error.code } : {},
    ...error.uncertain ? { uncertain: true } : {},
    ...recordValue(error).compatibilityRequired ? { compatibilityRequired: true } : {}
  });
}
function createComputerRouter(manager, workspaceRoots, agentStateReader) {
  const router = express.Router();
  router.use(express.json({ limit: "1mb" }));
  router.get("/capability", async (req, res) => {
    try {
      res.json(await manager.capability(req.query?.refresh === "1"));
    } catch (caught) {
      sendError(res, caught);
    }
  });
  router.post("/prepare", async (_req, res) => {
    try {
      res.json(await manager.prepare());
    } catch (caught) {
      sendError(res, caught);
    }
  });
  router.get("/", (req, res) => {
    try {
      const snapshot = manager.snapshot();
      const agentId = requestAgentId(req);
      res.json(agentId ? {
        ...snapshot,
        resources: snapshot.resources.filter((resource) => recordValue(resource).ownerAgentId === agentId)
      } : snapshot);
    } catch (caught) {
      sendError(res, caught);
    }
  });
  router.get("/events", (req, res) => {
    try {
      manager.requireEnabled();
    } catch (caught) {
      sendError(res, caught);
      return;
    }
    res.writeHead(200, {
      "Cache-Control": "no-cache, no-transform",
      Connection: "keep-alive",
      "Content-Type": "text/event-stream",
      "X-Accel-Buffering": "no"
    });
    const write = (event, value) => {
      res.write(`event: ${event}
data: ${JSON.stringify(value)}

`);
    };
    const onResources = (value) => write("resources", value);
    const onResource = (value) => write("resource", value);
    const onDeleted = (value) => write("deleted", value);
    manager.on("resources", onResources);
    manager.on("resource", onResource);
    manager.on("deleted", onDeleted);
    write("resources", manager.snapshot());
    req.on("close", () => {
      manager.off("resources", onResources);
      manager.off("resource", onResource);
      manager.off("deleted", onDeleted);
    });
  });
  router.post("/", (req, res) => {
    try {
      manager.requireEnabled();
      const body = recordValue(req.body);
      const callerAgentId = requestAgentId(req);
      const requestedAgentId = String(body.agentId || "").trim();
      if (callerAgentId && requestedAgentId && callerAgentId !== requestedAgentId) {
        res.status(403).json({ error: "Agent tools cannot create a Computer for another Agent" });
        return;
      }
      const agentId = callerAgentId || requestedAgentId;
      if (!agentId) {
        res.status(400).json({ error: "Computer owner Agent is required" });
        return;
      }
      const owner = ownerAgent(agentStateReader, agentId);
      if (!owner) {
        res.status(404).json({ error: "Computer owner Agent was not found" });
        return;
      }
      const root = workspaceRoots.resolve(String(body.rootId || ""));
      if (!root) {
        res.status(404).json({ error: "Computer Project workspace was not found" });
        return;
      }
      const ownerWorkspace = String(owner.projectWorkspace || owner.cwd || "").trim();
      if (!ownerWorkspace || ownerWorkspace !== root.canonicalPath) {
        res.status(409).json({ error: "Computer owner Agent is not bound to the selected Project workspace" });
        return;
      }
      res.json(manager.create({
        ownerAgentId: agentId,
        projectRootId: root.rootId,
        workspace: root.canonicalPath,
        name: body.name
      }));
    } catch (caught) {
      sendError(res, caught);
    }
  });
  router.patch("/:id", (req, res) => {
    try {
      assertRequestOwner(manager, req, req.params.id);
      res.json(manager.rename(req.params.id, recordValue(req.body).name));
    } catch (caught) {
      sendError(res, caught);
    }
  });
  for (const operation of ["start", "stop"]) {
    router.post(`/:id/${operation}`, async (req, res) => {
      try {
        assertRequestOwner(manager, req, req.params.id);
        res.json(await manager[operation](req.params.id));
      } catch (caught) {
        sendError(res, caught);
      }
    });
  }
  router.delete("/:id", async (req, res) => {
    try {
      assertRequestOwner(manager, req, req.params.id);
      res.json(await manager.delete(req.params.id));
    } catch (caught) {
      sendError(res, caught);
    }
  });
  router.post("/:id/control", (req, res) => {
    try {
      assertRequestOwner(manager, req, req.params.id);
      const owner = recordValue(req.body).owner;
      if (owner !== "agent" && owner !== "human") {
        res.status(400).json({ error: "Computer control owner must be agent or human" });
        return;
      }
      res.json(manager.takeControl(req.params.id, owner));
    } catch (caught) {
      sendError(res, caught);
    }
  });
  router.post("/:id/tool/:tool", async (req, res) => {
    try {
      assertRequestOwner(manager, req, req.params.id);
      res.json(await manager.callTool(
        req.params.id,
        req.params.tool,
        recordValue(req.body),
        requestAgentId(req) ? "agent" : "human"
      ));
    } catch (caught) {
      sendError(res, caught);
    }
  });
  router.get("/:id/viewer-config", (req, res) => {
    try {
      const config = manager.viewerConfig(req.params.id);
      res.json({
        password: config.password,
        viewOnly: config.viewOnly,
        generation: config.generation,
        controlEpoch: config.controlEpoch
      });
    } catch (caught) {
      sendError(res, caught);
    }
  });
  router.get("/:id/viewer/*", (req, res) => {
    try {
      const config = manager.viewerConfig(req.params.id);
      const viewerPath = `/${String(req.params[0] || "vnc.html").replace(/^\/+/, "")}`;
      const query = req.originalUrl.includes("?") ? req.originalUrl.slice(req.originalUrl.indexOf("?")) : "";
      const upstream = http.request({
        hostname: config.host,
        port: config.port,
        method: "GET",
        path: `${viewerPath}${query}`,
        headers: {
          Accept: req.get("Accept") || "*/*",
          "Accept-Encoding": "identity"
        }
      }, (response) => {
        res.status(response.statusCode || 502);
        for (const [name, value] of Object.entries(response.headers)) {
          if (value !== void 0 && !["content-security-policy", "x-frame-options"].includes(name)) {
            res.setHeader(name, value);
          }
        }
        response.pipe(res);
      });
      upstream.on("error", (error) => {
        if (!res.headersSent) res.status(502).json({ error: error.message });
        else res.end();
      });
      upstream.end();
    } catch (caught) {
      sendError(res, caught);
    }
  });
  router.get("/:id/viewer", (req, res) => {
    res.redirect(307, `${req.originalUrl.replace(/\/viewer(?:\?.*)?$/, "/viewer/vnc.html")}`);
  });
  return router;
}
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  createComputerRouter
});
